### PR TITLE
Write a script to generate data/manufacturer_data.py from the ESTA data and use it to update the current data

### PR DESCRIPTION
**Pull request by peternewman**
Simplifies resolving https://github.com/OpenLightingProject/rdm-app/issues/7 in future.

### CODE REVIEW

**Comment by peternewman** [comment]
Just need to test with accents, then we're good to go.

**Comment by nomis52** [comment]
Is this ok to merge?

**Comment by peternewman** [comment]
I sort of got blocked. I want to fix the issues with the admin UI before I commit more changes, but I've been rather busy at work recently. I still need to test with the accents too.

**Comment by daveol** [comment]
@peternewman I would wait for my merge before you start on that because otherwise git merge is gonna have problems I think

**Comment by peternewman** [comment]
Thanks for the heads up @daveol however I don't think it should be a problem, as you haven't touched the Python code (so far at least), so it should merge cleanly. I still need to test if the accents break the JS though, and if they do, you can fix it in your new PRs :).

**Comment by peternewman** [comment]
Now I need to get the duplicate 0x4C5A's fixed upstream.

**Comment by peternewman** [comment]
This is now ready for merging @nomis52 and I've raised a separate issue regarding foreign characters (  https://github.com/OpenLightingProject/rdm-app/issues/61 ).

**Comment by nomis52** [comment]
LGTM

**Comment by peternewman** [comment]
Can I trouble you to deploy this please @nomis52 as I still can't deploy currently due to a few issues.

**Pull request merged**
