### PR TITLE
A few more Robe PIDs

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
I need to work out why this is failing and fix it first...

**Comment by peternewman** [comment]
@vanous would you mind reviewing these before I merge if you've got time?

**Comment by vanous** [comment]
It looks good. Tomas says it's not complete, but i am not sure (when) he can export all the others... i am trying but cannot promise. Perhaps wait a few more days, then merge.

**Comment by peternewman** [comment]
Thanks @vanous .

You gave me a load of other PIDs here https://github.com/OpenLightingProject/rdm-app/pull/100#issuecomment-328076605 which I've formatted into a list in https://github.com/OpenLightingProject/rdm-app/issues/197 and will tick off as they get merged.

I was mostly hoping you could sanity check them and confirm any sub device targeting, or are they all root? And confirm things like DMC, although Googling suggests "During Movement Correction".

**Pull request merged**
