### PR TITLE
Manufacturer updates

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by kripton** [comment]
Do you plan to merge this at some point in time? Into master or 0.10?
What's the trigger that adds new commits to that branch?

**Comment by peternewman** [comment]
> Do you plan to merge this at some point in time? Into master or 0.10?

Funnily enough I was looking at this today too... Mostly to confirm Travis was broken here too so it probably also needs to switch to GitHub Actions.

Unfortunately without #206 I normally end up just spinning up a local copy of the webapp to download the updates into 0.10/master.

This becomes [manufacturer_names.proto](https://github.com/OpenLightingProject/ola/blob/master/data/rdm/manufacturer_names.proto) so it's only relevant for OLA master.

> What's the trigger that adds new commits to that branch?

Currently it's a cron job on my laptop hence the sporadic nature of it. I should really switch it to an automated GitHub action (unless yourself or someone else fancies giving that a go). It should probably still do a PR as sometimes the source data breaks in "fun" ways.

**Comment by kripton** [comment]
> Funnily enough I was looking at this today too... Mostly to confirm Travis was broken here too so it probably also needs to switch to GitHub Actions.
> 
> Unfortunately without #206 I normally end up just spinning up a local copy of the webapp to download the updates into 0.10/master.
> 
> This becomes [manufacturer_names.proto](https://github.com/OpenLightingProject/ola/blob/master/data/rdm/manufacturer_names.proto) so it's only relevant for OLA master.

Okay, the point of the exercise is to have an updated https://rdm.openlighting.org? Where is that hosted? If using Github actions to update that, Github pages might be the natural solution.
And since Github Actions can be used as "cron jobs"/scheduled periodically, why not?

> > What's the trigger that adds new commits to that branch?
> 
> Currently it's a cron job on my laptop hence the sporadic nature of it. I should really switch it to an automated GitHub action (unless yourself or someone else fancies giving that a go). It should probably still do a PR as sometimes the source data breaks in "fun" ways.

Yep, a cron job explains it, I was assuming some automated job. But it's a funny thing if the branch as a PR attached.
I'd need to check how to open a PR from a GitHub Action. Most probably possible, I just never did that before.

**Comment by peternewman** [comment]
> Okay, the point of the exercise is to have an updated https://rdm.openlighting.org?

Yes in theory, although there's a whole load of extra stuff there. I think some of our indexes aren't configured in the GitHub repo, as when I tried to push once before it broke the website, hence trying to go down the continuous deployment route instead, I'd almost got there and then Google added some extra steps where you have to build on the server side and need to sign up with a credit card (although there's a free tier). Which sort of feels like I need to dedicate some good time to it once I'm registered, and other bits keep getting in the way.

I guess the main point of the exercise is ensuring that what ends up in OLA master comes from some data that's committed to another repo primarily.

> Where is that hosted?

It's in Google App Engine as its a very dynamic site, people can upload their RDM model collector results and all sorts.

> If using Github actions to update that, Github pages might be the natural solution.

Agreed it would be if it was that dumb/flat.

> And since Github Actions can be used as "cron jobs"/scheduled periodically, why not?

Yeah, that was more what I meant about automating this "cron job".

> Yep, a cron job explains it, I was assuming some automated job. But it's a funny thing if the branch as a PR attached. I'd need to check how to open a PR from a GitHub Action. Most probably possible, I just never did that before.

It doesn't currently open the PR, I just do it manually, but having the commits GitHub at least flags it up. Yeah I'm sure PRs are possible and I think I've seen them elsewhere...

**Pull request merged**
