### PR TITLE
Addition sensor information PR 4 of 4

### PR DESCRIPTION
**Pull request by vanous**
last one.

### CODE REVIEW

**Comment by vanous** [comment]
Hi guys,

after sleeping over it and after half a dozen of hours with a chainsaw (this always helps:) ) i came back to say that i am sorry if this caused problem. You can probably disregard PR 1-3 and only use #4. 
If you want me to split it up to smaller chunks, let me know, i will try that.
thank you
Petr

**Comment by vanous** [comment]
All: we have been discussing further GDTF development with some other companies and the original idea to have RDM ids + sensor info, for which this scan would be nice to have, was replaced by having full RDM spec (for offline, visualizer purposes). This is now carried forward as the plan for action. All the little prep work on additional RDM collection stuff i did here, which i had hoped could help to make use of OLA as the tool to get that data is therefore useless and can be scraped.

**Comment by peternewman** [comment]
Has it updated since http://gdtf-share.com/wiki/GDTF_File_Description#RDM_Section then @vanous ? What's "full RDM spec (for offline, visualizer purposes)"? I suspect we could gather a lot of other RDM data still, or is this Carallon level with angles and other real world parameters?

**Comment by vanous** [comment]
Yes, this is the current spec, it was changed before the official release, I am just slow to keep up. It would be really nice to have the collection done with ola, I just know I cannot help as there is too much work :(

**Pull request closed without merging**
