### PR TITLE
Use a regex to detect bad UIDs

### PR DESCRIPTION
**Pull request by nomis52**

### CODE REVIEW

**Comment by peternewman** [comment]
LGTM, are you going to do the same to the EUIDs?

**Comment by nomis52** [comment]
Updated.

**Comment by peternewman** [comment]
I don't see any regex for the EUIDs

**Comment by nomis52** [comment]
You don't need one. I just made the parseInt bit strict.

**Comment by peternewman** [comment]
Ah I see, you've round tripped it.

**Pull request merged**
